var var_one = "Welcome...!";
document.write(var_one + "<br>");
var var_two;
var_two = "Hello";
document.write(var_two + "<br>");
var var_three = "".concat(var_one);
document.write(var_three + "<br>");
var var_four = true;
document.write(var_four + "<br>");
var var_five = 12.5;
document.write(var_five + "<br>");
var var_six = [10, 20, 30, 40, 50];
document.write(var_six + "<br>");
var var_seven = ['ABC', 'ANGULAR', 'BHG '];
document.write(var_seven + "<br>");
var var_eight = 'Typescript';
document.write(var_eight + "<br>");
var var_nine = [1, 2, 3, 'a', 'b', 'c', true, 10.5];
document.write(var_nine + "<br>");
